name: "my hello action"

description: "say hello with GitHub Actions"

inputs:
  first-greeting:
    description: "who would you like to greet in the console"
    required: true
    default: "Olga"
  second-greeting:
    description: "Another person to greet"
    required: true
    default: "Olga 2"
  third-greeting:
    description: "a third greeting"
    required: false
runs:
  using: "node12"
  main: "index.js"
